name: "Minikube workflow"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Minikube
      id: minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
      with:
        k8s-version: 1.17.0
        minikube-version: 1.6.2

    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}

    - name: Check Result
      run: |
        ./deploy-and-test.sh
